const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=fs.readFileSync(require('path').join(__dirname,'../main/mail-view.html'),'utf8');
const script=[...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)].at(-1)[1];
let opened,edited;const location={origin:'https://example.com',href:'',search:''};
const sandbox={console,URL,URLSearchParams,location,window:{CREDIPASS_FIREBASE:{db:{},functions:{}},open:(...x)=>opened=x},firebase:{auth:()=>({onAuthStateChanged:()=>{}})},document:{getElementById:()=>({textContent:'Bozza concreta'})},alert:x=>{throw Error(x)},prompt:()=> 'Risposta modificata'};
vm.createContext(sandbox);vm.runInContext(script,sandbox);
vm.runInContext(`currentPracticeId='molino';currentEmailId='mail1';currentPractice={cliente_nome:'Giuseppe',cliente_cognome:'Molino',cliente_email:'cliente@example.com',cliente_telefono:'+393331234567'};currentEmail={mittente:['bank@example.com'],replyTo:['referente@example.com'],destinatari:['consulente@example.com'],oggetto:'CU 2025',messageId:'<bank123@example.com>',aiAnalysis:{requestedDocuments:['CU 2025'],suggestedReply:'Grazie per la richiesta CU'}}`,sandbox);
sandbox.requestDocuments();assert.equal(location.href,'/main/dashboard-consulente.html?id=molino&integrazioneDaEmail=mail1');
assert.equal(sandbox.replyRecipient(),'referente@example.com');
sandbox.openMailClient();assert(opened[0].startsWith('https://mail.google.com/'));assert(decodeURIComponent(opened[0]).includes('rfc822msgid:bank123@example.com'));
sandbox.openWhatsApp();assert(opened[0].startsWith('https://wa.me/393331234567'));
sandbox.openPractice();assert.equal(location.href,'/main/dashboard-consulente.html?id=molino');
assert(html.includes('textarea id="suggestedReply"'));assert(!html.includes('prompt('));assert(html.includes('onclick="sendReply()"'));
console.log('PASS actions: same dashboard integration flow, reply-to, Gmail original, WhatsApp, fascicolo, inline editor and send button');
