/*
 * Seed iniziale domini banca.
 *
 * IMPORTANTE:
 * questa lista NON è considerata definitiva.
 * Il Mail Engine può proporre domini sconosciuti in
 * mail_domini_da_verificare e l'utente può confermarli una sola volta.
 */

const BANK_DOMAIN_SEED = [
  { bancaKey: "intesa_sanpaolo", bancaNome: "Intesa Sanpaolo", domains: ["intesasanpaolo.com", "isybank.com", "fideuram.it"] },
  { bancaKey: "unicredit", bancaNome: "UniCredit", domains: ["unicredit.it", "unicredit.eu"] },
  { bancaKey: "banco_bpm", bancaNome: "Banco BPM", domains: ["bancobpm.it", "webank.it", "alettibank.it"] },
  { bancaKey: "bper", bancaNome: "BPER Banca", domains: ["bper.it"] },
  { bancaKey: "mps", bancaNome: "Monte dei Paschi di Siena", domains: ["mps.it", "widiba.it"] },
  { bancaKey: "bnl", bancaNome: "BNL BNP Paribas", domains: ["bnl.it", "findomestic.it"] },
  { bancaKey: "credit_agricole", bancaNome: "Crédit Agricole Italia", domains: ["credit-agricole.it"] },
  { bancaKey: "credem", bancaNome: "Credem", domains: ["credem.it"] },
  { bancaKey: "banca_sella", bancaNome: "Banca Sella", domains: ["sella.it", "bancapatrimoni.it"] },
  { bancaKey: "fineco", bancaNome: "FinecoBank", domains: ["finecobank.com"] },
  { bancaKey: "ing", bancaNome: "ING Italia", domains: ["ing.it"] },
  { bancaKey: "illimity", bancaNome: "Illimity Bank", domains: ["illimity.com"] },
  { bancaKey: "mediobanca_premier", bancaNome: "Mediobanca Premier", domains: [
      "mediobancapremier.com",
      "mediobancapremier.it",
      "mediobancapremier.istruttorie.it",
      "istruttorie.mediobancapremier.it"
  ]},
  { bancaKey: "mediolanum", bancaNome: "Banca Mediolanum", domains: ["bancamediolanum.it"] },
  { bancaKey: "banca_generali", bancaNome: "Banca Generali", domains: ["bancagenerali.it"] },
  { bancaKey: "allianz_bank", bancaNome: "Allianz Bank", domains: ["allianzbank.it"] },
  { bancaKey: "zurich_bank", bancaNome: "Zurich Bank", domains: ["zurichbank.it"] },
  { bancaKey: "bbva", bancaNome: "BBVA Italia", domains: ["bbva.it"] },
  { bancaKey: "hype", bancaNome: "Hype", domains: ["hype.it"] },
  { bancaKey: "cherry_bank", bancaNome: "Cherry Bank", domains: ["cherrybank.it"] },
  { bancaKey: "n26", bancaNome: "N26", domains: ["n26.com"] },
  { bancaKey: "revolut", bancaNome: "Revolut", domains: ["revolut.com"] },
  { bancaKey: "wise", bancaNome: "Wise", domains: ["wise.com"] },
  { bancaKey: "banca_profilo", bancaNome: "Banca Profilo / Tinaba", domains: ["bancaprofilo.it", "tinaba.bancaprofilo.it"] },
  { bancaKey: "mediobanca", bancaNome: "Mediobanca", domains: ["mediobanca.com"] },
  { bancaKey: "banca_ifis", bancaNome: "Banca Ifis", domains: ["bancaifis.it"] },
  { bancaKey: "bff", bancaNome: "BFF Bank", domains: ["bff.com"] },
  { bancaKey: "finint", bancaNome: "Banca Finint", domains: ["bancafinint.com"] },
  { bancaKey: "banca_progetto", bancaNome: "Banca Progetto", domains: ["bancaprogetto.it"] },
  { bancaKey: "banca_cfplus", bancaNome: "Banca CF+", domains: ["bancacfplus.it"] },
  { bancaKey: "banca_sistema", bancaNome: "Banca Sistema", domains: ["bancasistema.it"] },
  { bancaKey: "guber", bancaNome: "Guber Banca", domains: ["guber.it"] },
  { bancaKey: "compass", bancaNome: "Compass", domains: ["compass.it"] },
  { bancaKey: "agos", bancaNome: "Agos", domains: ["agos.it"] },
  { bancaKey: "mcc", bancaNome: "Mediocredito Centrale", domains: ["mcc.it"] },
  { bancaKey: "ca_auto_bank", bancaNome: "CA Auto Bank", domains: ["ca-autobank.it"] },
  { bancaKey: "santander_consumer", bancaNome: "Santander Consumer Bank", domains: ["santanderconsumer.it"] },
  { bancaKey: "popso", bancaNome: "Banca Popolare di Sondrio", domains: ["popso.it"] },
  { bancaKey: "banco_desio", bancaNome: "Banco di Desio", domains: ["bancodesio.it"] },
  { bancaKey: "banca_asti", bancaNome: "Banca di Asti", domains: ["bancadiasti.it"] },
  { bancaKey: "sparkasse", bancaNome: "Sparkasse", domains: ["sparkasse.it"] },
  { bancaKey: "bapr", bancaNome: "Banca Agricola Popolare di Ragusa", domains: ["bapr.it"] },
  { bancaKey: "popolare_bari", bancaNome: "Banca Popolare di Bari", domains: ["popolarebari.it"] },
  { bancaKey: "bppb", bancaNome: "Banca Popolare di Puglia e Basilicata", domains: ["bppb.it"] },
  { bancaKey: "banca_piacenza", bancaNome: "Banca di Piacenza", domains: ["bancadipiacenza.it"] },
  { bancaKey: "banca_piemonte", bancaNome: "Banca del Piemonte", domains: ["bancadelpiemonte.it"] },
  { bancaKey: "valsabbina", bancaNome: "Banca Valsabbina", domains: ["bancavalsabbina.com"] },
  { bancaKey: "cassa_ravenna", bancaNome: "La Cassa di Ravenna", domains: ["lacassa.com"] },
  { bancaKey: "banca_imola", bancaNome: "Banca di Imola", domains: ["bancadiimola.it"] },
  { bancaKey: "carifermo", bancaNome: "Carifermo", domains: ["carifermo.it"] },
  { bancaKey: "banca_alba", bancaNome: "Banca d'Alba", domains: ["bancadalba.it"] },
  { bancaKey: "bcc_milano", bancaNome: "BCC Milano", domains: ["bccmilano.it"] },
  { bancaKey: "cassa_padana", bancaNome: "Cassa Padana", domains: ["cassapadana.it"] },
  { bancaKey: "bcc_brescia", bancaNome: "BCC Brescia", domains: ["bccbrescia.it"] },
  { bancaKey: "bcc_garda", bancaNome: "BCC del Garda", domains: ["bccgarda.it"] },
  { bancaKey: "bcc_treviglio", bancaNome: "BCC Treviglio", domains: ["bcctreviglio.it"] },
  { bancaKey: "banca_prealpi", bancaNome: "Banca Prealpi SanBiagio", domains: ["bancaprealpisanbiagio.it"] },
  { bancaKey: "centromarca", bancaNome: "Centro Marca Banca", domains: ["centromarcabanca.it"] },
  { bancaKey: "banca_marca", bancaNome: "Banca della Marca", domains: ["bancadellamarca.it"] },
  { bancaKey: "credifriuli", bancaNome: "CrediFriuli", domains: ["credifriuli.it"] },
  { bancaKey: "raiffeisen", bancaNome: "Raiffeisen", domains: ["raiffeisen.it"] },
  { bancaKey: "emil_banca", bancaNome: "Emil Banca", domains: ["emilbanca.it"] },
  { bancaKey: "bcc_felsinea", bancaNome: "BCC Felsinea", domains: ["bccfelsinea.it"] },
  { bancaKey: "romagnabanca", bancaNome: "RomagnaBanca", domains: ["romagnabanca.it"] },
  { bancaKey: "rivierabanca", bancaNome: "RivieraBanca", domains: ["rivierabanca.it"] },
  { bancaKey: "chiantibanca", bancaNome: "ChiantiBanca", domains: ["chiantibanca.it"] },
  { bancaKey: "bcc_roma", bancaNome: "BCC Roma", domains: ["bccroma.it"] },
  { bancaKey: "bcc_san_vincenzo", bancaNome: "BCC San Vincenzo de' Paoli", domains: ["bccsanvincenzo.it"] },
  { bancaKey: "campania_centro", bancaNome: "Banca Campania Centro", domains: ["bancacampaniacentro.it"] },
  { bancaKey: "bcc_napoli", bancaNome: "BCC Napoli", domains: ["bccnapoli.it"] },
  { bancaKey: "monte_pruno", bancaNome: "Banca Monte Pruno", domains: ["bccmontepruno.it"] },
  { bancaKey: "banca_2021", bancaNome: "Banca 2021", domains: ["banca2021.it"] },
  { bancaKey: "bcc_aquara", bancaNome: "BCC di Aquara", domains: ["bccaquara.it"] },
  { bancaKey: "bcc_flumeri", bancaNome: "BCC di Flumeri", domains: ["bccflumeri.it"] },
  { bancaKey: "bcc_buonabitacolo", bancaNome: "BCC di Buonabitacolo", domains: ["bccbuonabitacolo.it"] },
  { bancaKey: "bcc_capaccio", bancaNome: "BCC Capaccio Paestum e Serino", domains: ["bcccapaccio.it"] },
  { bancaKey: "bcc_magna_grecia", bancaNome: "BCC Magna Grecia", domains: ["bccmagnagrecia.it"] },
  { bancaKey: "credito_popolare", bancaNome: "Banca di Credito Popolare", domains: ["bcp.it"] },
  { bancaKey: "bcc_basilicata", bancaNome: "BCC Basilicata", domains: ["bccbasilicata.it"] },
  { bancaKey: "bcc_san_marzano", bancaNome: "BCC San Marzano", domains: ["bccsanmarzano.it"] },
  { bancaKey: "bcc_locorotondo", bancaNome: "BCC Locorotondo", domains: ["bcclocorotondo.it"] },
  { bancaKey: "bcc_mediocrati", bancaNome: "BCC Mediocrati", domains: ["mediocrati.it"] },
  { bancaKey: "banca_sicana", bancaNome: "Banca Sicana", domains: ["bancasicana.it"] },
  { bancaKey: "banca_don_rizzo", bancaNome: "Banca Don Rizzo", domains: ["bancadonrizzo.it"] },
  { bancaKey: "bcc_pachino", bancaNome: "BCC Pachino", domains: ["bccpachino.it"] },
  { bancaKey: "bcc_belpasso", bancaNome: "BCC Belpasso", domains: ["bccbelpasso.it"] },
  { bancaKey: "deutsche_bank", bancaNome: "Deutsche Bank Italia", domains: ["deutsche-bank.it"] },
  { bancaKey: "barclays", bancaNome: "Barclays", domains: ["barclays.it"] },
  { bancaKey: "credit_suisse", bancaNome: "Credit Suisse", domains: ["credit-suisse.com"] },
  { bancaKey: "ubs", bancaNome: "UBS", domains: ["ubs.com"] },
  { bancaKey: "societe_generale", bancaNome: "Société Générale", domains: ["societegenerale.it"] },
  { bancaKey: "citi", bancaNome: "Citibank", domains: ["citibank.it"] },
  { bancaKey: "jp_morgan", bancaNome: "J.P. Morgan", domains: ["jpmorgan.com"] },
  { bancaKey: "bank_of_america", bancaNome: "Bank of America", domains: ["bofa.com"] },
  { bancaKey: "state_street", bancaNome: "State Street", domains: ["statestreet.com"] },

  // domini PEC / gruppi cooperativi utili come seed generico
  { bancaKey: "gruppo_bcc_iccrea", bancaNome: "Gruppo BCC Iccrea", domains: ["gruppobcciccrea.it", "pec.gruppobcciccrea.it"] },
  { bancaKey: "cassa_centrale", bancaNome: "Cassa Centrale", domains: ["cassacentrale.it", "pec.cassacentrale.it"] }
];

module.exports = {
  BANK_DOMAIN_SEED,
};
